sudo: false
language: node_js
node_js:
  - '0.10'
before_install: npm install -g bower grunt-cli
before_script:
  - 'bower install'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6cfe200b39a0f4131485
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

